version: "3.8"

x-common-variables:
  read-only-workdir: &read-only-workdir
    type: bind
    source: .
    target: /workdir
    read_only: true

services:
  buf-lint:
    image: bufbuild/buf:0.51.0
    command: ["lint", "--verbose"]
    working_dir: /workdir
    volumes:
      - *read-only-workdir

  buf-breaking-change:
    image: bufbuild/buf:0.51.0
    command: ["breaking", "--against", "https://github.com/grapl-security/grapl.git", "--verbose"]
    working_dir: /workdir
    volumes:
      - *read-only-workdir
