# This file exists solely to coordinate the build of Grapl service
# containers.
#
# At the moment, these are "local" Grapl containers, and not
# necessarily identical to the artifacts we would use in real
# deployments.
version: "3.8"

services:

  ########################################################################
  # Python Services
  ########################################################################

  # should match `pulumi/infra/analyzer_executor.py`'s GraplDockerBuild
  analyzer-executor:
    image: grapl/analyzer-executor:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/Dockerfile
      target: analyzer-executor-deploy

  engagement-creator:
    image: grapl/engagement-creator:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/Dockerfile
      target: engagement-creator-deploy

  # This container build exists only for Local Grapl; if we are able
  # to deploy model-plugin-deployer as an actual Lambda there, we can
  # get rid of this.
  model-plugin-deployer:
    image: grapl/model-plugin-deployer:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/Dockerfile
      target: model-plugin-deployer-deploy

  ########################################################################
  # Web Services
  ########################################################################

  notebook:
    image: grapl/notebook:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/Dockerfile
      target: grapl-notebook

  ########################################################################
  # Utility Services
  ########################################################################

  pulumi:
    image: grapl/local-pulumi:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.pulumi

  localstack:
    image: grapl/localstack:${TAG:-latest}
    build:
      context: localstack
      dockerfile: Dockerfile

  provisioner:
    image: grapl/provisioner:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/python/lambdas.Dockerfile
      target: provisioner
