version: "3.8"

x-common-variables:
  read-only-workdir: &read-only-workdir
    type: bind
    source: .
    target: /workdir
    read_only: true
  read-write-workdir: &read-write-workdir
    type: bind
    source: .
    target: /workdir
    read_only: false

services:
  prettier:
    image: grapl/format
    build:
      context: ./etc/formatter
    working_dir: /workdir/etc/formatter
    entrypoint:
      ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail"]
    command:
      - "-c"
      - |
        echo "Do not run this service directly; it serves only as a source of common configuration!"
        exit 42

  buf-lint:
    image: bufbuild/buf:1.2.1
    command: ["lint", "--verbose"]
    working_dir: /workdir
    volumes:
      - *read-only-workdir

  buf-breaking-change:
    image: bufbuild/buf:1.2.1
    command:
      [
        "breaking",
        "--against",
        "https://github.com/grapl-security/grapl.git",
        "--verbose",
      ]
    working_dir: /workdir
    volumes:
      - *read-only-workdir

  # Use buf to check if our protobuf files are correctly formatted.
  buf-lint-format:
    image: bufbuild/buf:1.2.1
    # buf doesn't currently use exit codes properly; see comments in
    # this script for further details.
    command: .buildkite/scripts/check_protobuf_formatting.sh
    entrypoint: sh
    working_dir: /workdir
    volumes:
      - *read-only-workdir

  # Use buf to rewrite our protobuf files with the proper formatting.
  buf-format:
    image: bufbuild/buf:1.2.1
    command: ["format", "--verbose", "--write"]
    environment:
      # buf tries to write to `~/.cache`, which turns out to be
      # `/.cache` when running as a non-root user (as we need to do to
      # write formatted files back out owned by the workstation
      # user). We won't have permission to write to `/.cache`, so we
      # need to change our `HOME` directory to somewhere we *do* have
      # write permissions. This will result in a `.cache` directory in
      # the repository root, but it will actually allow this to
      # *work*, so it's a small price to pay.
      HOME: /workdir
    working_dir: /workdir
    volumes:
      - *read-write-workdir

  hcl-lint:
    image: docker.cloudsmith.io/grapl/releases/hcl-formatter:1.7.4
    command: lint
    volumes:
      - *read-only-workdir

  hcl-format:
    image: docker.cloudsmith.io/grapl/releases/hcl-formatter:1.7.4
    command: format
    volumes:
      - *read-write-workdir

  prettier-lint:
    extends:
      service: prettier
    command: ./format.sh --check
    volumes:
      - *read-only-workdir

  prettier-format:
    extends:
      service: prettier
    command: ./format.sh --update
    volumes:
      - *read-write-workdir
