[package]
name = "lens-subscriptions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
grapl-utils = { path = "../grapl-utils" }
grapl-config = { path = "../grapl-config" }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
sqlx = { version = "0.6", features = [
  "postgres",
  "runtime-tokio-rustls",
  "uuid",
  "offline",
  "json"
] }
rust-proto = { path = "../rust-proto", version = "*" }
tokio = { version = "1.20.0", features = ["full"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
async-trait = "0.1.56"
tonic = "0.7.2"
tokio-stream = "0.1.9"
futures = "0.3.21"
thiserror = "1.0.31"
dashmap = "5.3.4"
tracing = "0.1.35"
clap = { version = "3.0", default_features = false, features = [
  "std",
  "env",
  "derive"
] }
