[workspace]
members = [
  "./derive-dynamic-node",
  "./consul-connect",
  "./endpoint-plugin",
  "./lens-creator",
  "./event-source",
  "./generator-dispatcher",
  "./generators/sysmon-generator",
  "./generators/osquery-generator",
  "./graph-merger",
  "./graph-mutation-service",
  "./graph-query-service",
  "./grapl-config",
  "./grapl-graphql-codegen",
  "./grapl-web-ui",
  "./grapl-utils",
  "./kafka",
  "./lens-manager",
  "./lens-subscriptions",
  "./node-identifier",
  "./nomad-client-gen",
  "./organization-management",
  "./pipeline-ingress",
  "./plugin-bootstrap",
  "./plugin-executor",
  "./plugin-registry",
  "./plugin-sdk/generator-sdk/",
  "./plugin-work-queue",
  "./rust-proto",
  "./schema-manager",
  "./sysmon-parser",
  "./uid-allocator",
]

[profile.dev]
opt-level = 1

[profile.dev-local-grapl]
inherits = "dev"
# Remove this if you're trying to debug with gdb.
# Results in a ~20x binary size reduction, for example
# sysmon-generator: 279M -> 16M
strip = "debuginfo"
