[package]
name = "rust-proto-new"
version = "0.1.0"
authors = ["Grapl, Inc. <sales@graplsecurity.com>"]
edition = "2021"
description = "Wrapper library for Grapl's protocol buffers"
license = "MIT"

[dependencies]
bytes = "1.1"
futures = "0.3"
grapl-utils = { path = "../grapl-utils" }
prost = "0.10"
prost-types = "0.10"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "time"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = { version = "0.7", features = ["default", "compression", "tls"] }
tonic-health = "0.6"
tracing = "0.1"
uuid = { version = "0.8", features = ["v4"] }

[build-dependencies]
tonic-build = { version = "0.7", features = ["default", "compression"] }

[dev-dependencies]
proptest = "1.0"
quickcheck = "1.0"
quickcheck_macros = "1.0"
test-context = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = [
  "graph-mutation-full",
  "uid-allocator-full",
]
graph-mutation = []
graph-mutation-messages = ["graph-mutation"]
graph-mutation-server = ["graph-mutation", "graph-mutation-messages"]
graph-mutation-client = ["graph-mutation", "graph-mutation-messages"]
graph-mutation-full = [
  "graph-mutation-server",
  "graph-mutation-client",
  "graph-mutation-messages",
  "graph-mutation",
]

uid-allocator = []
uid-allocator-messages = ["uid-allocator"]
uid-allocator-server = ["uid-allocator-messages", "uid-allocator"]
uid-allocator-client = ["uid-allocator-messages", "uid-allocator"]
uid-allocator-full = [
  "uid-allocator-messages",
  "uid-allocator-client",
  "uid-allocator-server",
  "uid-allocator"
]
