[package]
name = "rust-proto-new"
version = "0.1.0"
authors = ["Grapl, Inc. <sales@graplsecurity.com>"]
edition = "2021"
description = "Wrapper library for Grapl's protocol buffers"
license = "MIT"

[dependencies]
async-trait = "0.1.53"
bytes = "1.1.0"
futures = "0.3.0"
prost = "0.9.0"
prost-types = "0.9.0"
thiserror = "1.0.30"
tonic = "0.6.1"
uuid = { version = "0.8.2", features = ["v4"] }

[build-dependencies]
tonic-build = { version = "0.6.0", features = ["prost"] }

[dev-dependencies]
proptest = "1.0.0"

[features]
uid-allocator = []
uid-allocator-messages = ["uid-allocator"]
uid-allocator-server = ["uid-allocator-messages", "uid-allocator"]
uid-allocator-client = ["uid-allocator-messages", "uid-allocator"]
uid-allocator-full = [
  "uid-allocator-messages",
  "uid-allocator-client",
  "uid-allocator-server",
  "uid-allocator"
]
