version: "3.8"

services:
  integration-tests:
    image: kafka-metrics-exporter/integration-tests:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: build-test
      args:
        - RUST_BUILD=test-integration

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      default:
        aliases:
          - zookeeper

  kafka-provision:
    image: confluentinc/cp-kafka:latest

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      default:
        aliases:
          - kafka

networks:
  default:
    name: kafka-metrics-exporter-test-net
