---
env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"

steps:
  - label: ":pulumi: Preview grapl/testing environment changes in Staging account"
    command:
      - .buildkite/shared/steps/pulumi_preview.sh grapl/grapl/testing
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            PULUMI_ACCESS_TOKEN: "pulumi-token"
      - "grapl-security/pulumi#v0.1.0":
          command: preview
          project_dir: pulumi/grapl
          stack: grapl/testing
    agents:
      queue: "pulumi-staging"

  - wait

  - label: ":pulumi: Update grapl/testing environment in Staging account"
    command:
      - .buildkite/shared/steps/pulumi_up.sh grapl/grapl/testing
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            PULUMI_ACCESS_TOKEN: "pulumi-token"
      - "grapl-security/pulumi#v0.1.0":
          command: update
          project_dir: pulumi/grapl
          stack: grapl/testing
    agents:
      queue: "pulumi-staging"

  - wait

  - trigger: "grapl-testing"
    label: ":rocket: Trigger testing pipeline"
    # Since this is asynchronous, this pipeline will pass or fail
    # based on whether the triggered pipeline passes or fails.
    async: false
    build:
      commit: "${BULIDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - label: ":writing_hand: Record successful build"
    command:
      - .buildkite/shared/steps/record_successful_pipeline_run.sh
