---
env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"

# This pipeline is for running tests against deployed infrastructure
# from our grapl/testing stack.

steps:
  # This step relies on Pulumi stack outputs to target the correct
  # deployment, so we need access to the token, and have to run in the
  # correct AWS account.
  - label: ":aws: E2E tests in AWS"
    command:
      - .buildkite/scripts/e2e_in_aws.sh testing
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            PULUMI_ACCESS_TOKEN: "pulumi-token"
    agents:
      queue: "pulumi-staging"
    # This test is notoriously flaky, in that it can take widely
    # varying amounts of time to complete, which can run afoul of the
    # (very) generous timeouts we have given it.
    retry:
      automatic:
        limit: 2
