---
env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"
  BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX: "secret/data/buildkite/env"

# This pipeline is for running tests against deployed infrastructure
# from our grapl/testing stack.

steps:
  - label: ":aws: E2E tests in AWS"
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - PULUMI_ACCESS_TOKEN
    command:
      - .buildkite/scripts/grapl_testing_stack/run_parameterized_job.sh e2e-tests 6
    # We don't believe the test is currently repeatable until we execute on
    # https://github.com/grapl-security/issue-tracker/issues/793
    # But we also don't want these failures blocking the pipeline.
    # Remove this once 793 is complete.
    soft_fail: true
