[package]
name = "grapl-aws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-stream = "0.3.2"
async-trait = "0.1.52"
futures-core = "0.3.19"
futures-util = "0.3.19"
grapl-config = { path = "../grapl-config" }
rusoto_core = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_s3 = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_sqs = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
thiserror = "1.0.30"
tokio = { version = "1.14.0", features = [
  "io-util",
  "sync",
  "rt",
  "macros",
  "time",
  "rt-multi-thread"
] }

[features]
integration = []
