[package]
name = "lens-creator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bytes = "1.1"
chrono = "0.4"
clap = { version = "3.0", default_features = false, features = [
    "std",
    "env",
    "derive"
] }
failure = "0.1"
futures = "0.3"
grapl-utils = { path = "../grapl-utils" }
grapl-config = { path = "../grapl-config" }

kafka = { path = "../kafka", version = "*" }
opentelemetry = { version = "0.16", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.15", features = [
    "collector_client",
    "rt-tokio"
] }

rust-proto = { path = "../rust-proto", version = "*" }
uid-allocator = { path = "../uid-allocator", default_features = false, features = [
    "client"
] }
serde = "1.0"
serde_dynamodb = { version = "0.9", default_features = false, features = [
    "rustls"
] }
sha2 = "0.9"
tap = "1.0"
thiserror = "1.0"
tokio = { version = "1.17", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-opentelemetry = "0.16"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid = { version = "1.0", features = ["v4"] }
blake2 = "0.10.4"

[dev-dependencies]
async-trait = "0.1"
quickcheck = "1.0"
quickcheck_macros = "1.0"
test-context = "0.1"
