[package]
name = "graph-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
grapl-config = { path = "../grapl-config", version = "*" }
fnv = "1.0.7"
serde = "1.0.136"
serde_json = "1.0.78"
tokio = { version = "1.16.1", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }

[dev-dependencies]
dgraph-tonic = "0.9.0"

[features]
integration = []
