[package]
name = "grapl-org-management"
version = "0.1.0"
edition = "2018"

[lib]

[[bin]] # Bin to run org management gRPC server
name = "orgmanagement-server"
path = "src/main.rs"


[dependencies]
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "0.4", features = ["serde", "v4"] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres" ] }
async-std = { version = "1.6", features = [ "attributes" ] }

[build-dependencies]
tonic-build = "0.5"
