[package]
name = "grapl-web-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", default_features = false, features = [
  "macros",
  "compress-brotli"
] }
awc = { version = "3", default_features = false, features = [
  "compress-brotli"
] }
actix-files = "0.6"
actix-session = "0.5"
argon2 = { version = "0.4", features = ["std"] }
chrono = { version = "0.4", default-features = false }
hmap = "0.1.0"
futures-util = "0.3"
rand = "0.8"
serde = "1"
serde_dynamodb = "0.9"
tap = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.2"
grapl-config = { path = "../grapl-config" }
rusoto_core = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_dynamodb = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
