[package]
name = "grapl-web-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
grapl-config = { path = "../grapl-config" }
actix-web = "3.3.2"
actix-files = "0.5.0"
actix-session = "0.4.1"
thiserror = "1.0.30"
argon2 = { version = "0.3.1", features = ["std"] }
futures = "0.3.18"
futures-util = "0.3.18"
rusoto_core = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
rusoto_dynamodb = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
tracing = "0.1.29"
tracing-subscriber = "0.3.2"
serde = "1.0.130"
serde_dynamodb = "0.9.0"
chrono = "0.4.19"
rand = "0.8.4"
tap = "1.0.1"
hmap = "0.1.0"
url = "2.2.2"
tokio = "1.14.0"
