[package]
name = "generator-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rust-proto = { path = "../../rust-proto" }
thiserror = "1.0.30"
tokio = { version = "1.14.0", features = ["full"] }
tonic = { version = "0.6.1", features = ["tls"] }
tonic-health = "0.5.0"
tracing = "0.1.29"
uuid = { version = "0.8.2", features = ["v4"] }
serde_json = "1.0.78"
serde = { version = "1.0.136", features = ["derive"] }
trust-dns-resolver = "0.20.3"

[features]
internal = ["client"]
client = []
