[package]
name = "plugin-registry"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "plugin-registry-service"
path = "src/main.rs"

[lib]
name = "plugin_registry"

[dependencies]
rust-proto = { path = "../rust-proto" }
