[package]
name = "grapl-tracing"
version = "0.0.1"
edition = "2021"

[dependencies]
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.17", features = [
  "collector_client",
  "rt-tokio"
] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-opentelemetry = "0.18"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
