[package]
name = "orgmanagement"
version = "0.1.0"
edition = "2018"

[lib]

[[bin]] # Bin to run org management gRPC server
name = "server"
path = "src/main.rs"

#[[bin]] # Bin to run org management gRPC client
#name = "client"
#path = "src/client.rs"

[dependencies]
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
sqlx = { version = "0.5", features = [
  "runtime-tokio-rustls",
  "postgres",
  "offline",
  "uuid"
] }
tracing-futures = "0.2.5"
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
grapl-config = { path = "../grapl-config", version = "*" }
thiserror = "1.0.26"

[build-dependencies]
tonic-build = "0.5"
