[package]
name = "grapl_model_plugin_deployer"
version = "0.1.0"
authors = ["todo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "grapl_model_plugin_deployer_lib"
path = "src/lib.rs"

[[bin]]
name = "grapl-model-plugin-deployer"
path = "src/main.rs"

[dependencies]
thiserror = "1"
rusoto_s3 = { version="0.46.0", default_features = false, features=["rustls"] }
rusoto_dynamodb = { version="0.46.0", default_features = false, features=["rustls"] }
uuid = { version = "0.8", features=["v4"] }

grapl-config = { path = "../grapl-config" }
grapl-graphql-codegen = { path = "../grapl-graphql-codegen" }


# Types for protobuf
bytes = "1.0"
prost = "0.7"
prost-derive = "0.7"

# Execution driving libs
async-stream = "0.3"

tokio = { version = "1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tokio-stream = "0.1"
tonic = { version="0.4" }
tower = { version = "0.4" }

# tracing support
tracing = "0.1.*"
tracing-futures = "0.2.*"
tracing-subscriber = "0.2.*"

# Health Checks
tonic-health = "0.3"


[build-dependencies]
tonic-build = { version="0.4", features = ["prost"] }

[dev-dependencies]
criterion = "0.3"
test-context = "0.1"
async-trait = "0.1"


[[bench]]
name = "grapl_model_plugin_deployer_benchmark"
harness = false

[features]
integration = []
