[package]
name = "rust-proto"
version = "0.2.10"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2021"
description = "A library for interacting with Grapl graphs"
license = "MIT"

[dependencies]
log = "0.4"
prost = "0.9.0"
prost-types = "0.9.0"
rand = "0.8"
serde = "1"
serde_derive = "1"
thiserror = "1.0.30"
tonic = "0.6.1"
tracing = "0.1.22"
uuid = { version = "0.8.2", features = ["v4"] }

[build-dependencies]
tonic-build = { version = "0.6.0", features = ["prost"] }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = { version = "1" }
tracing-subscriber = "0.2"

[features]
default = []
extra_assertions = []
