[package]
name = "graph-mutation-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-trait = "0.1.53"
dashmap = "5.2.0"
rust-proto-new = { path = "../rust-proto-new" }
scylla = "0.4.4"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.34"
uuid = { version = "0.8.0", features = ["v4"] }
uid-allocator = { path = "../uid-allocator", default-features = false, features = ["client"]}
grapl-utils = { path = "../grapl-utils" }

rusoto_dynamodb = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }

rusoto_core = { version = "0.47.0", default_features = false, features = [
  "rustls"
] }
serde_dynamodb = "0.9.0"
serde = "1.0.137"
lazy_static = "1.4.0"
lru = "0.7.6"
