[package]
name = "grapl-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.2.0"
chacha20 = "0.8.1"
rand_core = {version = "0.6.3", features=["getrandom"]}
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
thiserror = "1.0.30"
x25519-dalek = "1.2.0"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
uuid = { version = "0.8.2", features = ["v4"] }

[features]
