[package]
name = "schema-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-proto-new = { path = "../rust-proto-new", default-features = false, features = ["schema-manager-server"] }
grapl-graphql-codegen = { path = "../grapl-graphql-codegen" }

sqlx = { version = "0.5", features = [
    "runtime-tokio-rustls",
    "postgres",
    "time",
#    "offline",
    "uuid",
    "migrate",
] }
thiserror = "1.0.31"
uuid = { version = "0.8", default-features = false, features = ["v4"] }
tokio = { version = "1.19.2", features = ["full"] }
async-trait = "0.1.56"
dashmap = "5.3.4"
